### ISSUE TITLE
SilentGear weapons don't get attributes?

### ISSUE THREAD

**Issue by Derpford** [spoorn/SpoornWeaponAttributes#11]
I've spent 3 diamonds on upgrading a SilentGear katana, but it's not getting any new attributes. Meanwhile, the Parry This! mace took exactly one diamond to upgrade.

Is something bugged, or am I just having rotten luck?

**Comment by Derpford** [comment]
...and then the moment after I opened the issue, I went to try one more time and got a crit modifier. It's not a bug, false alarm.

**Comment by spoorn** [comment]
Rotten luck!

The default chances of rolling each attribute is something like 5% to not overpower items
