### ISSUE TITLE
[1.18.1] Some mods do not get attributes

### ISSUE THREAD

**Issue by kwpugh** [spoorn/SpoornWeaponAttributes#4]
Hi, nifty mod for Fabric.

I checked some of my weapon/tool mods with mixed results.

Gobber:  Tried Gobber, Nether Gobber, and End Gobber Sword - none got attributes

Easy Emerald & More: Tried Emerald, Ruby and Steel Sword - only the Ruby Sword got attributes

More Gems: Tried Citrine, Alexandrite, Spinel, and Mossianite Swords - only Alexandrite got attributes

The latest sources for all three mods are on GitHub for reference.  Feel free to stop by my Discord if you need to chat.

Regards.

Kevin

**Comment by kwpugh** [comment]
I also have Mytic Metals in my test pack.

Tried Celestial, Banglum, and Bronze - only Celestial got attributes.

**Comment by kwpugh** [comment]
Interestingly, the swa3 tag is on all the swords, but the tool tips don't reflect it.
![Screen Shot 2022-02-24 at 7 26 46 PM](https://user-images.githubusercontent.com/8809210/155636154-8d8ce6ba-24cd-45a7-87b2-6f0d16500912.png)

**Comment by kwpugh** [comment]
Also, logging in and out a few times and the tooltips on diamond go aways, although the tags appear to still be there.
![Screen Shot 2022-02-24 at 7 39 01 PM](https://user-images.githubusercontent.com/8809210/155637407-e6cce9b7-ab2f-47fb-a27c-d4473aee173d.png)
![Screen Shot 2022-02-24 at 7 39 24 PM](https://user-images.githubusercontent.com/8809210/155637422-923f8bda-1e2c-4885-abbc-abd606cc0ee8.png)

**Comment by spoorn** [comment]
Each attribute has a chance to apply when the weapon is added to your inventory, and only attempts it once: https://github.com/spoorn/SpoornWeaponAttributes/blob/main/config-documentation.json5#L5

The chance for each attribute to apply is rather low by default to not overpower weapons.

I'm working on adding a way to reroll attributes easily

**Comment by kwpugh** [comment]
oh, every weapon does not get something.  I misunderstood the concept.  So it would be normal that weapons can be crafted and get nothing.

**Comment by spoorn** [comment]
You could always set the attribute chance to 1.0 if you want to guarantee an attribute is always applied

**Comment by kwpugh** [comment]
Now I understand.  I was just checking to make sure it was compatible with my weapon/tool mods.  Very nice work.
![Screen Shot 2022-02-24 at 8 25 50 PM](https://user-images.githubusercontent.com/8809210/155642134-647e3546-9cb4-4b90-bbfa-d4776a3092f7.png)

With mods that have expensive or rare swords, having a "re-roll" item found in chests might be a nice option.

Great work.

**Comment by kwpugh** [comment]
Seems to work fine.

Thanks

**Comment by spoorn** [comment]
Added a reroll mechanic in the latest revision, please try it out!

**Comment by kwpugh** [comment]
Nice.  I tried it out, works great.  Lapis is a good choice
